title: Heroscape Builder
email: your-email@example.com
description: Welcome to a space dedicated to the creative and custom aspects of Heroscape. This site is designed to support and inspire creativity, offering resources for custom units, terrain, cards, play styles, and even alternate games using Heroscape components. The goal is to foster a community where imagination and innovation thrive within this fantastic game platform. Dive in and explore a variety of Heroscape cards in formats tailored to different preferences, and enjoy all that’s available to enhance your Heroscape experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heroscapebuilder.com"
github_username: abnoba12

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
