title: Heroscape Builder
email: your-email@example.com
description: Welcome to a space dedicated to the creative and custom aspects of Heroscape. This site is designed to support and inspire creativity, offering resources for custom units, terrain, cards, play styles, and even alternate games using Heroscape components. The goal is to foster a community where imagination and innovation thrive within this fantastic game platform. Dive in and explore a variety of Heroscape cards in formats tailored to different preferences, and enjoy all that’s available to enhance your Heroscape experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heroscapebuilder.com"
github_username: abnoba12
# Build settings
theme: minima
defaults:
  - scope:
      path: ""
    values:
      sectionstylesheet: "/assets/css/main.css"
  - scope:
      path: "cardGenerator"
    values:
      sectionstylesheet: "/assets/css/cardGenerator.css"
  - scope:
      path: "dataBuilder"
    values:
      sectionstylesheet: "/assets/css/dataBuilder.css"
